hi vinit-churi here
Limitly/Free-Copilot pull request #14
Opened 2023-04-09 06:13 UTC by vinit-churi

Thanks for the initiating the project to get Free Copilot, hope this pull request gets merged 😄

2023-04-09 06:20 UTC, InimicalPart requested changes
Hey there Vinit! Thank you so much for sending in a pull request! There are some changed I'd want before we merge it! It seems that you've edited the README.md file in the Contributors folder. You need to make a folder there with your GitHub username (vinit-churi) and then put whatever file you want in there!

Thank you so much for supporting this project ❤️

2023-04-09 06:33 UTC, vinit-churi commented
Hello, @InimicalPart I have made the changes that you requested please review 
![image](https://user-images.githubusercontent.com/39941072/230758272-3247c684-f19d-4eec-9cd2-511534e5cc7b.png)

2023-04-09 06:37 UTC, InimicalPart requested changes
Almost there Vinit! The changes look great, but it seems like instead of restoring your change in the README.md (the one in Contributors), you've deleted it. Please restore that file and we can merge your pull request!

2023-04-10 06:04 UTC, vinit-churi commented
![image](https://user-images.githubusercontent.com/39941072/230837474-4ad44f2d-e50e-46c1-b756-30eb9941a789.png)

2023-04-10 06:11 UTC, vinit-churi commented on Contributors/README.md
> +> ***DO NOT EDIT OR COMMIT TO ANYONE ELSE'S WORKSPACE, ESPECIALLY FILES LIKE THIS README***
I haven't changed anything in the file. the github diff tool is showing line change maybe because I'm using windows machine and you are using some other OS, in a file an invisible character called a line ending is inserted. Different operating systems handle line endings differently.

2023-04-10 06:14 UTC, closed without merging